### ISSUE TITLE
Why not LoadLibraryA and GetProcAddress with separate dll wrapper with C bindings?

### ISSUE THREAD

**Issue by xDShot** [icculus/steamshim#1]
question

**Comment by icculus** [comment]
The Free Software Foundation explicitly claims that wrapping something in a DLL doesn't make it acceptable to combine with GPL code.

They give the specific example of breaking something into a separate _process_ that communicates over a pipe as acceptable, though, so that's the design I went with here, since this was specifically to let GPL games use Steamworks.

**Comment by xDShot** [comment]
>The Free Software Foundation explicitly claims that wrapping something in a DLL doesn't make it acceptable to combine with GPL code.

Does it prohibit static and dynamic linking during compiling? What about loading library on runtime?

**Comment by icculus** [comment]
> Does it prohibit static and dynamic linking during compiling? What about loading library on runtime?

Yes, you can't directly combine closed-source code with GPL-licensed code without violating the GPL license, no matter how you link it (static, dynamic, or LoadLibrary()'d). The license doesn't consider code in another process talking to GPL'd code as combining code, even if it's a custom interface designed specifically for those two pieces of code to communicate.

The goal of this project wasn't to make a C-callable wrapper around Valve's C++ code, it was to make it so GPL'd games can use Steamworks.

**Comment by xDShot** [comment]
Thanks for clarification. I should give up of implementation idea...
